"""remove item model

Revision ID: 2aec72975d22
Revises: 0f61f2589652
Create Date: 2022-11-04 17:02:50.763337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aec72975d22'
down_revision = '0f61f2589652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
