"""Add hunter type

Revision ID: 58385e58fadd
Revises: 8ad4cc7f0f67
Create Date: 2023-01-26 17:26:09.394821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58385e58fadd'
down_revision = '8ad4cc7f0f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hunter', sa.VARCHAR(length=63), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hunter')
    # ### end Alembic commands ###
