"""Add token to user

Revision ID: 85f0256bb078
Revises: 4c35a8333dc7
Create Date: 2022-12-11 20:32:52.669509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f0256bb078'
down_revision = '4c35a8333dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=255), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
