"""Initial schema

Revision ID: 9f1dad681e28
Revises: 
Create Date: 2023-02-12 20:53:37.087177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1dad681e28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshtoken',
    sa.Column('id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('validity_timestamp', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtoken_id'), 'refreshtoken', ['id'], unique=False)
    op.create_index(op.f('ix_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False)
    op.create_index(op.f('ix_refreshtoken_validity_timestamp'), 'refreshtoken', ['validity_timestamp'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hunter', sa.VARCHAR(length=63), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=False)
    op.create_table('clan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clan_id'), 'clan', ['id'], unique=False)
    op.create_index(op.f('ix_clan_name'), 'clan', ['name'], unique=False)
    op.create_table('hunter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hunter_email'), 'hunter', ['email'], unique=False)
    op.create_index(op.f('ix_hunter_first_name'), 'hunter', ['first_name'], unique=False)
    op.create_index(op.f('ix_hunter_id'), 'hunter', ['id'], unique=False)
    op.create_index(op.f('ix_hunter_last_name'), 'hunter', ['last_name'], unique=False)
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mission_leader', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mission_leader'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_id'), 'mission', ['id'], unique=False)
    op.create_index(op.f('ix_mission_title'), 'mission', ['title'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('mission_hunters',
    sa.Column('hunter_id', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hunter_id'], ['hunter.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['mission.id'], )
    )
    op.create_table('squad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization'], ['clan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_squad_id'), 'squad', ['id'], unique=False)
    op.create_index(op.f('ix_squad_name'), 'squad', ['name'], unique=False)
    op.create_table('hunter_squads',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squad.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hunter_squads')
    op.drop_index(op.f('ix_squad_name'), table_name='squad')
    op.drop_index(op.f('ix_squad_id'), table_name='squad')
    op.drop_table('squad')
    op.drop_table('mission_hunters')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_mission_title'), table_name='mission')
    op.drop_index(op.f('ix_mission_id'), table_name='mission')
    op.drop_table('mission')
    op.drop_index(op.f('ix_hunter_last_name'), table_name='hunter')
    op.drop_index(op.f('ix_hunter_id'), table_name='hunter')
    op.drop_index(op.f('ix_hunter_first_name'), table_name='hunter')
    op.drop_index(op.f('ix_hunter_email'), table_name='hunter')
    op.drop_table('hunter')
    op.drop_index(op.f('ix_clan_name'), table_name='clan')
    op.drop_index(op.f('ix_clan_id'), table_name='clan')
    op.drop_table('clan')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_refreshtoken_validity_timestamp'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_user_id'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_id'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    # ### end Alembic commands ###
