"""Remove unncesary indexes

Revision ID: d044ba419295
Revises: 58385e58fadd
Create Date: 2023-01-26 17:27:48.336488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd044ba419295'
down_revision = '58385e58fadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_description', table_name='item')
    op.drop_index('ix_organization_description', table_name='organization')
    op.drop_index('ix_team_description', table_name='team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_team_description', 'team', ['description'], unique=False)
    op.create_index('ix_organization_description', 'organization', ['description'], unique=False)
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    # ### end Alembic commands ###
